# Generated by Django 2.2.6 on 2019-10-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_id', models.IntegerField(blank=True, null=True)),
                ('mac_number', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'current_devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentLocalDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_number', models.TextField()),
            ],
            options={
                'db_table': 'current_local_devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.IntegerField(blank=True)),
            ],
        ),
    ]
