# Generated by Django 2.2.6 on 2019-10-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191013_1448'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testmodel',
            table='test_model',
        ),
    ]
