# Generated by Django 2.2.6 on 2019-10-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191013_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
