# Generated by Django 2.2.6 on 2019-10-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_testmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={},
        ),
    ]
