# Generated by Django 2.2.6 on 2019-10-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191013_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestModel',
            new_name='TestModel1',
        ),
        migrations.AlterModelTable(
            name='testmodel1',
            table=None,
        ),
    ]
