# Generated by Django 2.2.6 on 2019-10-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191013_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.IntegerField(blank=True)),
                ('x', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel1',
        ),
    ]
