# Generated by Django 2.2.6 on 2019-10-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191013_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel2',
        ),
    ]
