# Generated by Django 2.2.6 on 2019-10-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_testmodel2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel2',
            options={},
        ),
    ]
