# Generated by Django 2.2.6 on 2019-10-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191013_1459'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testmodel2',
            table='test_model_2',
        ),
    ]
