# Generated by Django 2.2.6 on 2019-10-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191013_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel2',
        ),
    ]
