# Generated by Django 2.2.6 on 2019-10-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_testmodel2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testmodel2',
            table='test_model2',
        ),
    ]
